<?php

/**
 * @package     Extengen
 * @subpackage  CustomCode
 *
 * @copyright   Copyright (C) Yepr, Herman Peeren. All rights reserved.
 * @license     GNU General Public License version 3 or later; see LICENSE.txt
 */

declare(strict_types=1);

namespace Yepr\Component\Extengen\Administrator\CustomCode;

// phpcs:disable PSR1.Files.SideEffects
\defined('_JEXEC') or die;
// phpcs:enable PSR1.Files.SideEffects

/**
 * The places generated code leaves room for code that was not generated.
 *
 * A generator that covers everything does not exist, and the two usual answers
 * to that are both bad. Telling people to edit the output means the next run
 * destroys their work. Letting the generator write anything at all means the
 * model stops describing the extension.
 *
 * The answer here is a fixed, small vocabulary. Each slot is a named point in
 * one generated file where a body from the model is emitted, and nothing else
 * is offered. A closed list is the point: somebody reading the model can see
 * every place the generator was overruled, and the generator can tell whether
 * a piece of custom code still has anywhere to go.
 *
 * The code lives **in the model**, not in the output. That is what makes it
 * survive a regeneration by construction rather than by rescue, what puts it
 * in the same version history as the rest of the model, and what will let a
 * slot be replaced later by a nested sub-model that generates the same body -
 * at which point the slot disappears and nothing else has to move.
 *
 * `ProtectedRegionMerger` is the other half, and is a safety net rather than
 * the mechanism: it carries back edits somebody made in the output despite all
 * of this, so that a regeneration does not silently eat them.
 *
 * **Back end only, for now.** Every slot names exactly one generated file per
 * object, which is what lets a person say where their code will end up. The
 * site templates generate a second list model and a second details model with
 * the same method names, so a shared slot would put one body in two files
 * without saying so. Site slots would be their own ids, and wait until 1.12
 * settles whether the front end is in v1 at all.
 *
 * @since  1.0.0
 */
final class SlotCatalogue
{
    /**
     * The marker tag stamped into generated files.
     *
     * Named for this generator, because a file generated by one tool should
     * not carry another tool's marker: two generators over one tree would
     * otherwise each treat the other's regions as its own.
     *
     * @since  1.0.0
     */
    public const TAG = 'extengen';

    /**
     * Every slot, by id.
     *
     * `owner` is the kind of model object whose form offers it, and decides
     * where in the model a body is stored. `pageType` narrows a Page slot to
     * one kind of page, because an index page has no save() to extend and a
     * details page has no list query. `indent` is how deep the markers sit in
     * the generated file - one tab for the class body, two inside a method -
     * because a marker that does not line up with the code around it reads as
     * debris rather than as an invitation.
     *
     * @var array<string, array{indent: int, owner: string, pageType?: string, label: string, description: string}>
     *
     * @since  1.0.0
     */
    private const SLOTS = [
        'table.check' => [
            'indent'      => 2,
            'owner'       => 'Entity',
            'label'       => 'Extra checks before saving',
            'description' => 'Runs at the end of the table\'s check(), where $this holds the row about to be'
                . ' stored. Return false to refuse it, after calling setError() to say why.',
        ],
        'table.methods' => [
            'indent'      => 1,
            'owner'       => 'Entity',
            'label'       => 'Extra methods on the table class',
            'description' => 'Whole methods, added to the end of the table class.',
        ],
        'listmodel.query' => [
            'indent'      => 2,
            'owner'       => 'Page',
            'pageType'    => 'indexpage',
            'label'       => 'Extra conditions on the list query',
            'description' => 'Runs at the end of getListQuery(), where $query is the query about to be'
                . ' returned and $db the database it will run against.',
        ],
        'listmodel.methods' => [
            'indent'      => 1,
            'owner'       => 'Page',
            'pageType'    => 'indexpage',
            'label'       => 'Extra methods on the list model',
            'description' => 'Whole methods, added to the end of the list model class.',
        ],
        'detailsmodel.methods' => [
            'indent'      => 1,
            'owner'       => 'Page',
            'pageType'    => 'detailspage',
            'label'       => 'Extra methods on the details model',
            'description' => 'Whole methods, added to the end of the details model class.',
        ],
    ];

    /**
     * Every slot id, in a stable order.
     *
     * @return string[]
     *
     * @since  1.0.0
     */
    public function ids(): array
    {
        return array_keys(self::SLOTS);
    }

    /**
     * The slots one kind of object may fill.
     *
     * @param  string   $owner     `Entity` or `Page`.
     * @param  ?string  $pageType  Narrows Page slots; null offers all of them.
     *
     * @return array<string, array{indent: int, owner: string, pageType?: string, label: string, description: string}>
     *
     * @since  1.0.0
     */
    public function for(string $owner, ?string $pageType = null): array
    {
        return array_filter(
            self::SLOTS,
            static fn (array $slot): bool => $slot['owner'] === $owner
                && ($pageType === null || !isset($slot['pageType']) || $slot['pageType'] === $pageType)
        );
    }

    /**
     * @since  1.0.0
     */
    public function has(string $id): bool
    {
        return isset(self::SLOTS[$id]);
    }

    /**
     * @return array{indent: int, owner: string, pageType?: string, label: string, description: string}
     *
     * @since  1.0.0
     */
    public function get(string $id): array
    {
        if (!isset(self::SLOTS[$id])) {
            throw new \OutOfBoundsException('There is no slot called "' . $id . '".');
        }

        return self::SLOTS[$id];
    }
}
